#!/bin/bash

#This is only for Unix platform

if [ $# -gt 0 ]; then
  if [ "$1" != "help" ] && [ "$1" != "build" ]; then
    echo -e "\033[31;1m\
  Unknown argument $1!\033[0m"
    exit 255
  fi
fi

if [ "$1" = "help" ] || [ "$1" = "-h" ]; then
  if [ "$2" = "pdf" ]; then
    open ./docs/README.pdf
  else
    open README.md
  fi
  exit 0
fi

size=$(stty size)
# shellcheck disable=SC2206
size_arr=($size)
row=${size_arr[0]}
col=${size_arr[1]}

if ((row < 30)) || ((col < 100)); then
  echo -e "\033[31;1m\
  Console Size ${row} ${col} Unsatisfied!\n\
  Minimum Requirement: 30 100
  Please Resize Console or Font Size.\033[0m"
  exit 2
fi

if [ "$1" = "build" ]; then
  if ! mvn -v >/dev/null; then
    echo -e "\033[32;1m\
  You don't have maven on your local machine.\n\
  Use provided apache-maven-3.8.6 for building.\033[0m"

    if ! tar -xzf ./lib-maven/apache-maven-3.8.6-bin.tar.gz; then
      echo -e "\033[31;1m\
  Unable to extract file ./lib-maven/apache-maven-3.8.6-bin.tar.gz\n\
  Please manually install Apache-Maven or add it to PATH\n\
  You are recommended to use a package manager (Homebrew, apt-get, pacman, snap...)\n\
  Use the following command (e.g., for Homebrew users):\n\
    \033[32;1m  brew install maven\033[31;1m\n\
  Official link: https://maven.apache.org/download.cgi\033[0m"
      exit 1
    fi
    rm -rf ./lib-maven/apache-maven-3.8.6
    mv apache-maven-3.8.6 ./lib-maven
    mvn_path=./lib-maven/apache-maven-3.8.6/bin/
  fi

  if [ "$2" = "testing" ]; then
    ${mvn_path}mvn clean package appassembler:assemble
  elif [ "$2" = "clean" ]; then
    ${mvn_path}mvn clean
  else
    ${mvn_path}mvn clean package appassembler:assemble -DskipTests
  fi
fi

bin_path=./target/appassembler/bin/
stty cbreak && ${bin_path}JungleApp
# shellcheck disable=SC2181
if [ $? != 0 ]; then
  if [ "$1" != "build" ]; then
    echo -e "\033[31;1m\
  It seems that you have not built the software.\n\
  Use the following command to build & run:
    ./run build\033[0m"
  else
    echo -e "\033[31;1m\
  The minimum requirement of this software is Java17.\n\
  Please update to Java17 (LTS) or higher!
  Official link: https://www.oracle.com/java/technologies/downloads/\033[0m"
  fi
fi
stty icanon
